Global:
  debug: false
  use_gpu: true
  epoch_num: 500
  log_smooth_window: 20
  print_batch_step: 50
  save_model_dir: ./output/rec/class_demo/
  save_epoch_step: 10
  eval_batch_step:
  - 0
  - 1000
  cal_metric_during_train: true
  pretrained_model: pretrain_models/ch_ppocr_server_v2.0_rec_pre/best_accuracy
  checkpoints: null
  save_inference_dir: ./
  use_visualdl: true
  infer_img: doc/imgs_words_en/word_10.png
  character_dict_path: ppocr/utils/ppocr_keys_v1.txt
  max_text_length: 25
  infer_mode: false
  use_space_char: false
  save_res_path: ./output/rec/predicts_ic15.txt
Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Cosine
    learning_rate: 0.001
    warmup_epoch: 1
  regularizer:
    name: L2
    factor: 1.0e-05
Architecture:
  model_type: rec
  algorithm: CRNN
  Transform: null
  Backbone:
    name: MobileNetV3
    scale: 1
    model_name: large
    small_stride:
    - 1
    - 2
    - 2
    - 2
  Neck:
    name: SequenceEncoder
    encoder_type: rnn
    hidden_size: 96
  Head:
    name: CTCHead
    fc_decay: 0
Loss:
  name: CTCLoss
PostProcess:
  name: CTCLabelDecode
Metric:
  name: RecMetric
  main_indicator: acc
Train:
  dataset:
    name: SimpleDataSet
    data_dir: ./train_data/rec_data_lesson_demo/
    label_file_list:
    - ./train_data/rec_data_lesson_demo/train.txt
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - RecAug: null
    - CTCLabelEncode: null
    - RecResizeImg:
        image_shape:
        - 3
        - 32
        - 100
    - KeepKeys:
        keep_keys:
        - image
        - label
        - length
  loader:
    shuffle: true
    batch_size_per_card: 512
    drop_last: true
    num_workers: 8
    use_shared_memory: false
Eval:
  dataset:
    name: SimpleDataSet
    data_dir: ./train_data/rec_data_lesson_demo/
    label_file_list:
    - ./train_data/rec_data_lesson_demo/train.txt
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - CTCLabelEncode: null
    - RecResizeImg:
        image_shape:
        - 3
        - 32
        - 100
    - KeepKeys:
        keep_keys:
        - image
        - label
        - length
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 512
    num_workers: 4
    use_shared_memory: false
profiler_options: null
